# 1. Base Image: Mulai dari image Python yang ringan
FROM python:3.10-slim

# 2. Set Working Directory di dalam container
WORKDIR /app

# 3. Salin file requirements & install library
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 4. Salin SEMUA file proyek (app.py DAN folder templates)
COPY . .

# 5. Beri tahu Docker bahwa container ini akan berjalan di port 5000
EXPOSE 5000

# 6. Perintah default untuk menjalankan server web
CMD ["python", "app.py"]